services:
  sync:
    container_name: atlassian-hubspot-sync
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - sync-data:/usr/src/app/data
    restart: unless-stopped

volumes:
  sync-data:
